import express from 'express';
import helmet from 'helmet';
import archiver from 'archiver';
import { join } from 'node:path';
import { readFile, stat } from 'node:fs/promises';
import { createReadStream } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { extract, cleanup } from './lib/extractor.js';

const __dirname = fileURLToPath(new URL('.', import.meta.url));

const app = express();
app.use(helmet({
  contentSecurityPolicy: {
    directives: {
      defaultSrc: ["'self'"],
      scriptSrc: ["'self'", "'unsafe-inline'"],
      styleSrc: ["'self'", "'unsafe-inline'", 'https:'],
      imgSrc: ["'self'", 'data:'],
      fontSrc: ["'self'", 'https:', 'data:'],
    }
  },
  crossOriginResourcePolicy: false
}));
app.use((req, res, next) => {
  console.log(new Date().toISOString(), req.method, req.url);
  next();
});
app.use(express.json({ limit: '50mb' }));
app.use(express.static(join(__dirname, 'public')));

app.post('/api/extract', async (req, res) => {
  try {
    const { url } = req.body;
    if (!url || !/^https?:\/\/.+/.test(url)) {
      return res.status(400).json({ error: 'Valid URL required (http:// or https://)' });
    }
    const result = await extract(url);
    const totalSize = result.files.reduce((s, f) => s + f.size, 0);
    const fileList = result.files.map(f => f.relPath);
    res.json({
      title: result.title,
      url: result.url,
      jobId: result.jobId,
      files: fileList,
      totalFiles: result.files.length,
      totalSize
    });
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.get('/api/download/:jobId', async (req, res) => {
  const { jobId } = req.params;
  try {
    const { extract } = await import('./lib/extractor.js');
    const JOBS_DIR = join((await import('node:os')).tmpdir(), 'we-jobs');
    const outDir = join(JOBS_DIR, jobId);

    await stat(outDir); // verify exists

    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="website-${jobId.slice(0, 8)}.zip"`);

    const archive = archiver('zip', { zlib: { level: 5 } });
    archive.pipe(res);

    async function addFiles(dir, basePath = '') {
      const { readdir, stat } = await import('node:fs/promises');
      const entries = await readdir(dir, { withFileTypes: true });
      for (const entry of entries) {
        const fullPath = join(dir, entry.name);
        const relPath = basePath ? join(basePath, entry.name) : entry.name;
        if (entry.isDirectory()) {
          if (entry.name !== '..' && entry.name !== '.') {
            await addFiles(fullPath, relPath);
          }
        } else {
          archive.file(fullPath, { name: relPath });
        }
      }
    }

    const hostname = new URL(req.query.url || 'https://unknown').hostname;
    const hostDir = join(outDir, hostname);
    try {
      await stat(hostDir);
      await addFiles(hostDir);
    } catch {
      await addFiles(outDir);
    }

    archive.append(`Website extracted from: ${req.query.url || 'Unknown'}\r\nGenerated by Website Extractor\r\n`, { name: 'README.txt' });

    await archive.finalize();
    cleanup(jobId);
  } catch (e) {
    res.status(404).json({ error: 'Job not found or expired' });
  }
});

const PORT = process.env.PORT || 3000;
const HOST = process.env.HOST || '0.0.0.0';
app.listen(PORT, HOST, () => {
  console.log(`Website Extractor running on http://${HOST}:${PORT}`);
});
